### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Sashimi0343** [Sashimi0343/furima-35172#9]
フリマアプリ達成要件の実装が全て完了致しました。
最終確認をお願い致します。
以下はテスト用に用意した各情報です。
宜しくお願い致します。

# URL
https://furima-35172.herokuapp.com/

# BASIC
ID：admin
PASS：0343

# 出品者用アカウント
email：test1@test
pass：test1000

# 購入者用アカウント
email：test2@test
pass：test2000

**Comment by snkw-works** [comment]
@Sashimi0343 さん、お待たせいたしました。ご提出ありがとうございます‼︎
問題なく正常に動作することが確認できました！　**LGTM**です✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）
最終課題発表会では、今までの成果を十分に発揮することができるよう、私達も応援しております🍀

**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
![最終課題終了_おめでとう画像_new1](https://user-images.githubusercontent.com/54050089/120949488-9cc71980-c77f-11eb-9257-c4c19ca282bf.png)

**Comment by Sashimi0343** [comment]
ありがとうございますっ！
